version: '3.4'

services:
  pwnarrativesqa:
    image: pwnarrativesqa
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - :9323
